### ISSUE TITLE
[Info > Notice] For posts created for the all domain, the name is not visible on the notice Edit page

### ISSUE THREAD

**Issue by sulmoJ** [spaceone-dev/feedback#144]

**Comment by JeoungSulMo** [comment]
Written by a system user for the all domain. I think the input tag should show a value other than domain Id.

![Image](https://user-images.githubusercontent.com/50662170/187616152-9f61b5b6-bd81-4091-b684-6410130a6497.png)
---
시스템 유저가 전체 도메인 대상으로 작성한 글입니다. 노출 대상에 domain_id 대신 다른 값이 필요해 보입니다.
